### ISSUE TITLE
TypeError: Can't modify immutable headers.

### ISSUE THREAD

**Issue by leandro-manifesto** [borderless/fetch-cors#2]
I'm getting "TypeError: Can't modify immutable headers." on Cloudflare Workers after integrating this library.

I believe the correct way is to implement response header mutation is to create a new Response instead of setting them in-place.

**Comment by blakeembrey** [comment]
It sounds like you’re returning an immutable response object that this library is trying to use. I’m going to have to suggest you clone it yourself, I don’t like the idea of every middleware I write cloning the response each time - if only because I’m not familiar with whether that would have any performance concerns.

**Comment by blakeembrey** [comment]
It’s very easy to clone yourself:

```js
return new Response(res)
```

**Comment by blakeembrey** [comment]
It’s very easy to clone yourself:

```js

```
